version: "3.9"

services:
  nexi_sistema:
    container_name: nexi_sistema
    build: .
    ports:
      - "40001:40001"
    volumes:
      # Banco de dados
      - ./Bancodados:/app/Bancodados

      # Uploads, fotos, m√≠dias
      - ./uploads:/app/uploads
    restart: always
    environment:
      TZ: "America/Sao_Paulo"
